---
- name: Install ansible selinux support library
  package:
    name: libselinux-python3
    state: present
  register: status
  until: status is succeeded
  become: true
  tags:
    - always

- name: Install ansible selinux configure libraries
  package:
    name:
      - python3-policycoreutils
      - python3-libsemanage
    state: present
  register: status
  until: status is succeeded
  become: true
  when: ansible_selinux.status == 'enabled'
  tags:
    - always
